[workspace]

members = [
  "ch3-flappy-dragon",
  "ch5-dungeon-crawler",
  "ch6-dungeon-denizens",
  "ch7-take-turns",
  "ch8-combat",
  "ch9-victory-and-defeat",
  "ch10-fov",
  "ch11-maps",
  "ch12-themes",
  "ch13-inventory",
]
